String.toLocaleString({

	"it": {
    "%game-intro"           : "Join the <strong>Cupcakes!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-CUPCAKES #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : '1',
    '%4'                    : '2',
    '%8'                    : '3',
    '%16'                   : '4',
    '%32'                   : '5',
    '%64'                   : '6',
    '%128'                  : '7',
    '%256'                  : '8',
    '%512'                  : '9',
    '%1024'                 : '10',
    '%2048'                 : '11',
    '%4096'                 : '12',
    '%8192'                 : '13',
    '%p0'                   : '1',
    '%p4'                   : '2',
    '%p8'                   : '3',
    '%p16'                  : '4',
    '%p32'                  : '5',
    '%p64'                  : '6',
    '%p128'                 : '7',
    '%p256'                 : '8',
    '%p512'                 : '9',
    '%p1024'                : '10',
    '%p2048'                : '11',
    '%p4096'                : '12',
    '%p8192'                : '13'

	},

  "en": {
    "%game-intro"           : "Join the <strong>Cupcakes!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-CUPCAKES #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : '1',
    '%4'                    : '2',
    '%8'                    : '3',
    '%16'                   : '4',
    '%32'                   : '5',
    '%64'                   : '6',
    '%128'                  : '7',
    '%256'                  : '8',
    '%512'                  : '9',
    '%1024'                 : '10',
    '%2048'                 : '11',
    '%4096'                 : '12',
    '%8192'                 : '13',
    '%p0'                   : '1',
    '%p4'                   : '2',
    '%p8'                   : '3',
    '%p16'                  : '4',
    '%p32'                  : '5',
    '%p64'                  : '6',
    '%p128'                 : '7',
    '%p256'                 : '8',
    '%p512'                 : '9',
    '%p1024'                : '10',
    '%p2048'                : '11',
    '%p4096'                : '12',
    '%p8192'                : '13'
  }

});
